### ISSUE TITLE
Detailed guide on compiling from source

### ISSUE THREAD

**Issue by dynabler** [philippta/flyscrape#40]
How do I compile Flyscrape from source? The docs say:

`go install github.com/philippta/flyscrape/cmd/flyscrape@latest`

But I downloaded a zip file, unpacked, changed some code and did
`go build`

I also did `go build flyscrape.go/scrape.go etc.` 

And nothing happened. Am I missing something?

**Comment by philippta** [comment]
Note: You do not have to download the source code from GitHub (as zip) in order to install flyscrape from source. The Go compiler (which you will install) does all that for you behind the scenes.

1. Download and install the Go compiler by following the official installation instructions: https://go.dev/doc/install
2. Open a new Terminal / Command Prompt and enter the go install command: `go install github.com/philippta/flyscrape/cmd/flyscrape@latest`
3. Once the command has finished you should find the compiled program in either ~/go/bin/flyscrape (if you are on Mac or Linux) or C:\Users\yourusername\go\bin\flyscrape (if you are on Windows)
4. You can run it from there or copy it wherever you like.

**Comment by dynabler** [comment]
The second set of command is what I was looking for. I managed to get a flyscrape.exe. But can't get it to run:

`cache: failed to create cache table: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub`

What's the solution?

**Comment by philippta** [comment]
With the latest v0.9.0 release, there is no longer a dependency on CGO and sqlite.

This means building from source should be very easy now.

Simply download the source code, open a terminal window in that directory and run:
```
go build ./cmd/flyscrape
```
